services:
  client:
    build:
      context: ./CLIENT
      dockerfile: Dockerfile
    image: iuh-ai-client:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  server:
    build:
      context: ./SERVER
      dockerfile: Dockerfile
    image: iuh-ai-server:latest
    environment:
      GOOGLE_API_KEY: "${GOOGLE_API_KEY}"
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      SERPER_API_KEY: "${SERPER_API_KEY}"
      LANGSMITH_TRACING: "${LANGSMITH_TRACING}"
      LANGSMITH_ENDPOINT: "${LANGSMITH_ENDPOINT}"
      LANGSMITH_PROJECT: "${LANGSMITH_PROJECT}"
      LANGSMITH_API_KEY: "${LANGSMITH_API_KEY}"
      USER_AGENT: "${USER_AGENT}"
      PINECONE_API_KEY: "${PINECONE_API_KEY}"
      PINECONE_INDEX_NAME: "${PINECONE_INDEX_NAME}"
      MONGO_URI: "${MONGO_URI}"
      MONGO_DB_NAME: "${MONGO_DB_NAME}"
      MONGO_COLLECTION_NAME: "${MONGO_COLLECTION_NAME}"
      UPSTASH_VECTOR_REST_URL: "${UPSTASH_VECTOR_REST_URL}"
      UPSTASH_VECTOR_REST_TOKEN: "${UPSTASH_VECTOR_REST_TOKEN}"
      PERPLEXITY_API_KEY: "${PERPLEXITY_API_KEY}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT}"
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
